name: Perks
version: '${project.version}'
main: com.rappytv.perks.PerkPlugin
api-version: '1.19'
depend:
  - RyLib
softdepend:
  - Vault

commands:
  perks:
    aliases: [ perk ]
    permission: perks.menu

permissions:
  perks.*:
    default: op
    children:
      perks.reload:
        default: op
      perks.quickUnlock:
        default: op
      perks.manage.add:
        default: op
      perks.manage.remove:
        default: op
      perks.manage.enable:
        default: op
      perks.manage.disable:
        default: op
      perks.menu:
        default: true