name: Perks
version: '${project.version}'
main: com.rappytv.perks.PerkPlugin
api-version: '1.19'
depend:
  - RyLib
softdepend:
  - Vault

commands:
  perks:
    aliases: [ perk ]
    permission: perks.command

permissions:
  perks.*:
    default: op
    children:
      perks.reload:
        default: op
      perks.command:
        default: true
      perks.quickUnlock:
        default: op