name: Perks
version: '${project.version}'
main: com.rappytv.perks.Perks
api-version: '1.19'
softdepend:
  - Vault

commands:
  perks:
    aliases: [ perk ]
    permission: esntls.perks

permissions:
  perks.*:
    default: op
    children:
      perks.reload:
        default: op
      perks.command:
        default: true